# Used Car Price Prediction
## About Dataset
The used car market in India is a dynamic and ever-changing landscape. Prices can fluctuate wildly based on a variety of factors including the make and model of the car, its mileage, its condition and the current market conditions. As a result, it can be difficult for sellers to accurately price their cars.

This dataset contains information about used cars.
This data can be used for a lot of purposes such as Used Car Price Prediction using different Machine Learning Techniques.

Data Description (Feature Information)

1. car_name: Car's Full name, which includes brand and specific model name.
2. brand: Brand Name of the particular car.
3. model: Exact model name of the car of a particular brand.
4. seller_type: Which Type of seller is selling the used car
5. fuel_type: Fuel used in the used car, which was put up on sale.
6. transmission_type: Transmission used in the used car, which was put on sale.
7. vehicle_age: The count of years since car was bought.
8. mileage: It is the number of kilometer the car runs per litre.
9. engine: It is the engine capacity in cc(cubic centimeters)
10. max_power: Max power it produces in BHP.
11. seats: Total number of seats in car.
12. selling_price: The sale price which was put up on website.

In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [45]:
df = pd.read_csv("cardekho_dataset.csv")
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [46]:
df.columns

Index(['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
       'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
       'max_power', 'seats', 'selling_price'],
      dtype='object')

## Feature Engineering
### Data Cleaning
1. Handling Missing values
2. Handling Duplicates
3. check data types
4. Understand the data

In [47]:
df.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

1. dropping the car_name column and brand column becouse it gives the same info about model

In [49]:
df.drop('car_name' , axis=1 , inplace=True)
df.drop('brand' , axis=1 , inplace=True)

In [50]:
df.head()

,Unnamed: 0,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [51]:
df.model.unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [52]:
df.drop("Unnamed: 0" , axis=1 , inplace=True)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   model              15411 non-null  object
 1   vehicle_age        15411 non-null  int64
 2   km_driven          15411 non-null  int64
 3   seller_type        15411 non-null  object
 4   fuel_type          15411 non-null  object
 5   transmission_type  15411 non-null  object
 6   mileage            15411 non-null  float64
 7   engine             15411 non-null  int64
 8   max_power          15411 non-null  float64
 9   seats              15411 non-null  int64
 10  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 1.3+ MB

### Getting all different types of features

In [54]:
# NUmerical features
num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print("Number of Numerical features : " , len(num_features))

# Categorical features
cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print("Number of Categorical Feature : " , len(cat_features))

# Discrete Features
discrete_features = [feature for feature in df.columns if len(df[feature].unique()) <= 25]
print("Number of Discrete Feature : " , len(discrete_features))

# Continous Features
continious_features = [feature for feature in df.columns if len(df[feature].unique()) > 25]
print("Number of Continous Feature : " , len(continious_features))

Number of Numerical features :  7
Number of Categorical Feature :  4
Number of Discrete Feature :  5
Number of Continous Feature :  6

## Train Test Split

In [55]:
from sklearn.model_selection import train_test_split
X = df.drop("selling_price" , axis=1)
y = df[['selling_price']]

In [56]:
y.head()

   selling_price
0         120000
1         550000
2         215000
3         226000
4         570000

## Feature Encoding and Scaling

In [57]:
len(df['model'].unique())

120

In [58]:
df['model'].value_counts()

model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

### Label Encoding of model column

In [59]:
X['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [60]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['model'] = le.fit_transform(X['model'])

In [61]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [62]:
len(df['seller_type'].unique()) , len(df['fuel_type'].unique()) , len(df['transmission_type'].unique())

(3, 5, 2)

In [63]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)
X_train.shape , y_train.shape , X_test.shape , y_test.shape

((10787, 10), (10787, 1), (4624, 10), (4624, 1))

In [64]:
# Create column transformer with 3 types of Transformer
num_features = X.select_dtypes(exclude='object').columns
onehot_columns = ['seller_type' , 'fuel_type' , 'transmission_type']

from sklearn.preprocessing import StandardScaler , OneHotEncoder
from sklearn.compose import ColumnTransformer

numeric_transformers = StandardScaler()
oh_transformers = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
   [
       ("OneHotEncoder" , oh_transformers , onehot_columns) ,
        ("StandardScalar" , numeric_transformers , num_features)
   ] , remainder='passthrough'
)

In [65]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [66]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.297402,-0.676545,-0.343638,0.089591,0.031822,-0.270404,-0.401881
1,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.535105,0.326647,1.556160,0.665139,-0.164146,-0.269702,-0.401881
2,1.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.830284,0.661045,1.315680,0.024842,-0.039264,-0.385057,-0.401881
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.709970,-0.342147,0.113276,0.151942,-0.546477,-0.401202,-0.401881
4,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.957510,-0.342147,-0.656263,-0.661018,0.210499,0.492388,-0.401881
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10782,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.555238,0.326647,1.742076,0.240672,-0.448493,-0.268064,2.077440
10783,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.902501,1.664236,0.089228,-0.881645,0.223948,0.068874,-0.401881
10784,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.040024,0.326647,-0.848647,0.178321,-0.928807,-0.777216,-0.401881
10785,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.535105,-1.345339,-0.968888,-0.279718,-0.546477,-0.430450,-0.401881
10786,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.050320,-1.345339,-0.608167,0.123165,-0.037343,0.070044,-0.401881

## Model Training and Model Selection

In [67]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.linear_model import LinearRegression , Ridge , Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error , root_mean_squared_error

### Evalute Model Function

In [68]:
# Create a function to evaluate model
def evaluate_model(true , predicted) :
    mse = mean_squared_error(true , predicted)
    mae = mean_absolute_error(true , predicted)
    rmse = root_mean_squared_error(true , predicted)
    r2_square = r2_score(true , predicted)
    return mae , mse , rmse , r2_square

### Begining Model Training

In [69]:
models = {
    "Linear Regression" : LinearRegression() ,
    "Lasso" : Lasso() ,
    "Ridge" : Ridge() , 
    "K Nearest Neighbours" : KNeighborsRegressor() , 
    "Decision Tree" : DecisionTreeRegressor() ,
    "Random Forest" : RandomForestRegressor() ,
    "AdaBoost Regressor" : AdaBoostRegressor() ,
}

for i in range(len(list(models))) :
    model = list(models.values())[i]
    model.fit(X_train , y_train)

    # make Prediction
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluate train and test datasets
    model_train_mse , model_train_mae , model_train_rmse , model_train_r2 = evaluate_model(y_train , y_train_pred)
    model_test_mse , model_test_mae , model_test_rmse , model_test_r2 = evaluate_model(y_test , y_test_pred)

    print(list(models.keys())[i])

    print("Model Performance for Training Set.")
    print("Root Mean Squared Error : {:.4f}".format(model_train_rmse) )
    print("Mean Squared Error : {:.4f}".format(model_train_mse) )
    print("Mean Absolute Error : {:.4f}".format(model_train_mae) )
    print("R2 Score : {:.4f}".format(model_train_r2) )

    print(' ' * 10 )
    print("Model Performance for Test Set.")
    print("Root Mean Squared Error : {:.4f}".format(model_test_rmse) )
    print("Mean Squared Error : {:.4f}".format(model_test_mse) )
    print("Mean Absolute Error : {:.4f}".format(model_test_mae) )
    print("R2 Score : {:.4f}".format(model_test_r2) )

    print("-"* 70)

Linear Regression
Model Performance for Training Set.
Root Mean Squared Error : 559313.7144
Mean Squared Error : 268437.6549
Mean Absolute Error : 312831831093.0353
R2 Score : 0.6183

Model Performance for Test Set.
Root Mean Squared Error : 507556.7988
Mean Squared Error : 281329.9042
Mean Absolute Error : 257613903997.1093
R2 Score : 0.6575
----------------------------------------------------------------------
Lasso
Model Performance for Training Set.
Root Mean Squared Error : 559313.7247
Mean Squared Error : 268436.6045
Mean Absolute Error : 312831842665.8283
R2 Score : 0.6183

Model Performance for Test Set.
Root Mean Squared Error : 507555.9600
Mean Squared Error : 281329.3439
Mean Absolute Error : 257613052501.5833
R2 Score : 0.6575
----------------------------------------------------------------------
Ridge
Model Performance for Training Set.
Root Mean Squared Error : 559314.5335
Mean Squared Error : 268393.5790
Mean Absolute Error : 312832747356.4186
R2 Score : 0.6183

Model Performance for Test Set.
Root Mean Squared Error : 507540.1071
Mean Squared Error : 281277.1712
Mean Absolute Error : 257596960324.4093
R2 Score : 0.6575
----------------------------------------------------------------------
K Nearest Neighbours
Model Performance for Training Set.
Root Mean Squared Error : 332564.0080
Mean Squared Error : 92877.4265
Mean Absolute Error : 110598819430.7963
R2 Score : 0.8651

Model Performance for Test Set.
Root Mean Squared Error : 281596.3559
Mean Squared Error : 116515.2519
Mean Absolute Error : 79296507667.7390
R2 Score : 0.8946
----------------------------------------------------------------------
Decision Tree
Model Performance for Training Set.
Root Mean Squared Error : 20329.7436
Mean Squared Error : 4728.8897
Mean Absolute Error : 413298475.0162
R2 Score : 0.9995

Model Performance for Test Set.
Root Mean Squared Error : 381441.4050
Mean Squared Error : 131741.7622
Mean Absolute Error : 145497545477.8961
R2 Score : 0.8065
----------------------------------------------------------------------
Random Forest
Model Performance for Training Set.
Root Mean Squared Error : 131162.7008
Mean Squared Error : 39821.9428
Mean Absolute Error : 17203654083.3308
R2 Score : 0.9790

Model Performance for Test Set.
Root Mean Squared Error : 245304.4971
Mean Squared Error : 105351.8056
Mean Absolute Error : 60174296273.5142
R2 Score : 0.9200
----------------------------------------------------------------------
AdaBoost Regressor
Model Performance for Training Set.
Root Mean Squared Error : 397597.9548
Mean Squared Error : 290927.1816
Mean Absolute Error : 158084133623.6611
R2 Score : 0.8071

Model Performance for Test Set.
Root Mean Squared Error : 476621.2456
Mean Squared Error : 315907.3345
Mean Absolute Error : 227167811720.2343
R2 Score : 0.6979
----------------------------------------------------------------------

In [70]:
knn_params = {
    "n_neigbours" : [2 ,3 ,10 , 20 , 30 , 40 , 50] ,
}

rf_params = {
    "max_depth" : [5 ,8 , 10 , 15 , None] ,
    "max_features" : [5 ,7 , 'auto' , 8] ,
    "min_samples_split" : [2 ,8 ,15 , 20] ,
    "n_estimators" : [100 , 200 , 500 ,1000]
}

ada_params = {
    "n_estimators" : [30 , 40 , 50 , 60 , 80 , 90 , 110] ,
    "loss" : ['linear' , "square" , "exponetial"]
}

Model List for Hyper parameter tunning

In [ ]:
random_models = [
    
    ("AB" , AdaBoostRegressor() , ada_params)
]

##  HyperParameter Tunning

In [73]:
from sklearn.model_selection import RandomizedSearchCV
model_params = {} 

for name , model , params in random_models :
    random = RandomizedSearchCV(
        estimator=model ,
        param_distributions=params ,
        n_iter=100 ,
        cv = 3 ,
        verbose=2 ,
        n_jobs = 1
    )

    random.fit(X_train , y_train)
    model_params[name] = random.best_params_

    for model_name in model_params :
        print('------------Best Params for {model_name}------------------')
        print(model_params[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=1000; total time=   9.1s
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=1000; total time=   7.4s
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=1000; total time=   6.6s
[CV] END max_depth=5, max_features=7, min_samples_split=20, n_estimators=1000; total time=   8.3s
[CV] END max_depth=5, max_features=7, min_samples_split=20, n_estimators=1000; total time=  11.5s
[CV] END max_depth=5, max_features=7, min_samples_split=20, n_estimators=1000; total time=   9.0s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=1000; total time=  21.2s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=1000; total time=  33.5s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=1000; total time=  35.9s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=1000; total time=  46.9s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=1000; total time=  30.7s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=1000; total time=  34.2s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=200; total time=   2.5s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=200; total time=   2.3s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=200; total time=   2.4s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=500; total time=   4.8s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=500; total time=   4.6s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=500; total time=   3.2s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=500; total time=   5.3s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=500; total time=   5.2s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=500; total time=   5.1s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.4s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.9s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.8s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=1000; total time=  19.8s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=1000; total time=  22.3s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=1000; total time=  27.0s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=1000; total time=  26.3s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=1000; total time=  24.2s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=1000; total time=  21.7s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=100; total time=   1.2s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=100; total time=   1.2s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=100; total time=   1.2s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.8s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.8s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.8s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=8, min_samples_split=20, n_estimators=100; total time=   1.3s
[CV] END max_depth=10, max_features=8, min_samples_split=20, n_estimators=100; total time=   1.4s
[CV] END max_depth=10, max_features=8, min_samples_split=20, n_estimators=100; total time=   1.4s
[CV] END max_depth=5, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.7s
[CV] END max_depth=5, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.8s
[CV] END max_depth=5, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.7s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.8s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.9s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.8s
[CV] END max_depth=10, max_features=7, min_samples_split=2, n_estimators=200; total time=   3.5s
[CV] END max_depth=10, max_features=7, min_samples_split=2, n_estimators=200; total time=   2.9s
[CV] END max_depth=10, max_features=7, min_samples_split=2, n_estimators=200; total time=   2.9s
[CV] END max_depth=10, max_features=8, min_samples_split=20, n_estimators=200; total time=   3.0s
[CV] END max_depth=10, max_features=8, min_samples_split=20, n_estimators=200; total time=   3.0s
[CV] END max_depth=10, max_features=8, min_samples_split=20, n_estimators=200; total time=   3.8s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   4.0s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   3.2s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   4.6s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=500; total time=   9.7s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=500; total time=   8.4s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=500; total time=   8.2s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=500; total time=   4.4s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=500; total time=   4.3s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=500; total time=   4.5s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=100; total time=   0.9s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=100; total time=   0.9s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=100; total time=   0.9s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=100; total time=   2.6s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=100; total time=   2.9s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=100; total time=   2.2s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=1000; total time=  26.5s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=1000; total time=  27.0s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=1000; total time=  28.1s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=200; total time=   2.1s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=200; total time=   2.7s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=200; total time=   2.5s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=100; total time=   2.6s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=100; total time=   2.1s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=100; total time=   1.7s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=500; total time=   9.9s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=500; total time=  13.2s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=500; total time=  12.7s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=500; total time=   3.8s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=500; total time=   4.1s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=500; total time=   5.1s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=100; total time=   2.5s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=100; total time=   3.1s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=100; total time=   3.5s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=100; total time=   2.5s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=100; total time=   2.1s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=100; total time=   1.5s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=200; total time=   7.0s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=200; total time=   8.5s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=200; total time=   7.0s
[CV] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=1000; total time=  23.5s
[CV] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=1000; total time=  19.5s
[CV] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=1000; total time=  21.6s
[CV] END max_depth=None, max_features=7, min_samples_split=20, n_estimators=500; total time=   9.3s
[CV] END max_depth=None, max_features=7, min_samples_split=20, n_estimators=500; total time=   6.6s
[CV] END max_depth=None, max_features=7, min_samples_split=20, n_estimators=500; total time=   6.6s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=100; total time=   1.4s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=100; total time=   1.5s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=100; total time=   1.4s
[CV] END max_depth=None, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=  11.7s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=  13.4s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=  12.1s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=200; total time=   2.1s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=200; total time=   2.3s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=200; total time=   2.1s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.9s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.9s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=500; total time=   7.4s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=500; total time=   7.0s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=500; total time=   7.0s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=   8.9s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=   9.8s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=   8.8s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.9s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.9s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.9s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.8s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.8s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.9s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=1000; total time=   9.9s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=1000; total time=   8.4s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=1000; total time=   8.5s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=500; total time=   9.9s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=500; total time=   9.9s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=500; total time=   8.4s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=100; total time=   1.2s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=100; total time=   1.2s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=100; total time=   1.1s
[CV] END max_depth=10, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=500; total time=   4.9s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=500; total time=   5.1s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=500; total time=   5.1s
[CV] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=1000; total time=  11.5s
[CV] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=1000; total time=  12.3s
[CV] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=1000; total time=  11.5s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=500; total time=   7.0s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=500; total time=   6.8s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=500; total time=   7.0s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.9s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.9s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.9s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   1.0s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=200; total time=   2.4s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=200; total time=   2.3s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=200; total time=   2.3s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=1000; total time=   7.1s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=1000; total time=   6.8s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=1000; total time=   6.1s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=100; total time=   1.4s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=100; total time=   1.4s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=1000; total time=  15.8s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=1000; total time=  11.6s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=1000; total time=  10.8s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=200; total time=   1.3s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=200; total time=   1.4s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=200; total time=   1.3s
[CV] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=500; total time=   5.0s
[CV] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=500; total time=   5.4s
[CV] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=500; total time=   5.1s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=1000; total time=  14.9s

ValueError: Invalid parameter 'n_neigbours' for estimator KNeighborsRegressor(). Valid parameters are: ['algorithm', 'leaf_size', 'metric', 'metric_params', 'n_jobs', 'n_neighbors', 'p', 'weights'].